{{- if .Values.clusterRBAC.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "neo4j-aura-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "neo4j-aura-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "neo4j-aura-controller.chart" . }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
rules:
- apiGroups:
  - "neo4j.infra.doodle.com"
  resources:
  - aurainstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "neo4j.infra.doodle.com"
  resources:
  - aurainstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - patch
  - update
  - list
  - watch
  - delete
{{- end }}
