name: pr-gorelaser

permissions: {}

on:
  pull_request:
    branches:
      - 'master'

jobs:
  validate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Validate .goreleaser.yaml
        uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 # v6.2.1
        with:
          version: latest
          args: check
        env:
          RUNNER_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ secrets.DOODLE_OSS_BOT}}
